language: python
python:
  - "3.4"
  - "2.7"
install:
  - pip install --upgrade setuptools -r requirements.txt
  - pip install coveralls
script:
  - python setup.py test
  - python setup.py flake8
after_success:
  - coveralls
